### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by WouterDeKort** [ToxicGlobe/VSTS-SSIS-Extension#2]
It seems that this repository is empty. There is no code or a Wiki. 

Was this by mistake or has this extension been retired?

**Comment by schwaizi** [comment]
Hi, the extension will get update. Let say the site is under maintenance gor few days.

**Comment by blastdan** [comment]
Is there any risk that the plugin won't be maintained, or have a large shift in it's usage? I'm interested in using it, but don't want to start down the path to have it be changed significantly.

Thanks!

**Comment by schwaizi** [comment]
Hi, there will be two versions. One for TFS 2015-2017 and 2018. I will probably not continue to maintain the older version.
Anyway you still have the option to not update the Extension on your system. Since TFS2017 is available versioning of the task in TFS and you able to keep the specific version.

**Comment by blastdan** [comment]
Cool!

Anyway to put the WIki backup in the interim? I'd love to have access to the documentation.

**Comment by schwaizi** [comment]
Wiki will be populated in few days with the new version

**Comment by schwaizi** [comment]
Task updated. Info in Marketplace
